/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HTTP_INTERCEPTORS, HttpClient, provideHttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { BooksService } from './services/books.service';
import { AuthenticationService } from './services/authentication.service';
import { FeedbackService } from './services/feedback.service';
import { CommonModule } from '@angular/common';
import { CodeInputModule } from "angular-code-input";

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [
    CodeInputModule
  ],
  exports: [],
  declarations: [],
  providers: [
    BooksService,
    AuthenticationService,
    FeedbackService,
    ApiConfiguration,
    CommonModule,
    HttpClient
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
